### ISSUE TITLE
fix setup instructions

### ISSUE THREAD

**Issue by netdjw** [scssyworks/ng-lint-report#3]
Hi there!

I started try to use your package and found one mistakes in the instructions. The correct setup is looks like this:

```json
    "lint": "ng lint --format json --silent > jsonOutput.json",
    "report": "ng-lint-report --jsonfile jsonOutput.json",
    "ng-lint": "npm run lint && npm run report",
```

So I added the `--silent` paramter to `ng lint` command. Without this the `ng lint` is put some texts to the file what occurs JSON parse errors.

**Comment by scssyworks** [comment]
@netdjw I have updated the instructions
