### ISSUE TITLE
command not found: ng-lint-report

### ISSUE THREAD

**Issue by Dushan** [scssyworks/ng-lint-report#5]
I have done the setup as instructed. but it doesn't print the output to the HTML file (says 0 errors). when I run the below command it says command not found,
ng-lint-report --jsonfile jsonOutput.json

Below is my package.json

{
  "name": "appname",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --max_old_space_size=10000 --prod",
    "build-prod": "node --max_old_space_size=6144 node_modules/@angular/cli/bin/ng build",
    "test": "ng test",
    "lint": "ng lint --format json > jsonOutput.json",
    "e2e": "ng e2e",
    "lint:styles": "stylelint \"apps/**/*.scss\" && stylelint \"libs/**/*.scss\"",
    "lint-staged": "lint-staged",
    "report": "ng-lint-report --jsonfile jsonOutput.json"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.13",
    "@angular/cdk": "^9.0.1",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/forms": "~9.1.12",
    "@angular/material": "^9.0.0",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.0.1",
    "@ngrx/effects": "^9.1.0",
    "@ngrx/router-store": "^9.1.0",
    "@ngrx/schematics": "^11.0.0",
    "@ngrx/store": "^9.1.0",
    "@ngrx/store-devtools": "^9.1.0",
    "@swimlane/ngx-datatable": "^17.1.0",
    "@syncfusion/ej2-angular-calendars": "^18.4.41",
    "angular-bem": "^2.2.0",
    "angular-moment": "^1.3.0",
    "angular-gridster2": "^10.1.7",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.5.3",
    "jquery": "^3.5.1",
    "mat-daterangepicker": "^1.0.1",
    "material-expansion-panel": "^1.0.0",
    "moment": "^2.29.1",
    "ng-dynamic-component": "^8.0.0",
    "ngx-daterangepicker-material": "^4.0.1",
    "ngx-mat-select-search": "3.2.0",
    "ngx-material-timepicker": "^5.5.3",
    "ngx-moment": "^5.0.0",
    "popper.js": "^1.16.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "husky": "^4.3.8",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^5.0.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "lint-staged": "^11.1.2",
    "ng-lint-report": "^0.1.11",
    "prettier": "2.2.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

**Comment by scssyworks** [comment]
If you've installed it locally then you need to run it with `npx`.

```sh
npx ng-lint-report --jsonfile jsonOutput.json
```

else you can try with the npm script `npm run report`. Let me know if it still doesn't work!

**Comment by scssyworks** [comment]
I have pushed the latest version which brings support for eslint. Hopefully it should resolve your issue.
